// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: env_vars.sql

package sqlc

import (
	"context"
)

const createEnvVar = `-- name: CreateEnvVar :one
INSERT INTO env_vars (
  project_id, key, value
) VALUES (
  ?, ?, ?
)
RETURNING id, project_id, "key", value, created_at, updated_at
`

type CreateEnvVarParams struct {
	ProjectID int64
	Key       string
	Value     string
}

func (q *Queries) CreateEnvVar(ctx context.Context, arg CreateEnvVarParams) (EnvVar, error) {
	row := q.db.QueryRowContext(ctx, createEnvVar, arg.ProjectID, arg.Key, arg.Value)
	var i EnvVar
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
