// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Deployment struct {
	ID         int64
	ProjectID  int64
	DeployedAt sql.NullTime
	Status     string
	StartedAt  time.Time
}

type EnvVar struct {
	ID        int64
	ProjectID int64
	Key       string
	Value     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Project struct {
	ID          int64
	Name        string
	Description sql.NullString
	GithubURL   interface{}
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
