// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"
)

type Deployment struct {
	ID         int64
	ProjectID  int64
	DeployedAt sql.NullTime
	Status     string
	StartedAt  time.Time
}

type EnvVar struct {
	ID        int64
	ProjectID int64
	Key       string
	Value     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Project struct {
	ID            int64
	Name          string
	Description   sql.NullString
	GithubUrl     interface{}
	RepoName      string
	ContainerPort sql.NullInt64
	HostPort      sql.NullInt64
	ImageID       sql.NullString
	ContainerID   sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
